### ISSUE TITLE
Need Clarification on CSV Files for BayLum Package

### ISSUE THREAD

**Issue by ruribev** [crp2a/BayLum#32]
Hello,

I am trying to use the BayLum package and I am having difficulty understanding the structure and content of the following files that are required for importing data from a BINX-file:

- DiscPos.csv
- DoseEnv.csv
- DoseSource.csv
- rule.csv

Could you provide some guidance or examples on how these files should be structured and what kind of data they should contain?

Any help would be greatly appreciated.

Thank you

**Comment by RLumSK** [comment]
Dear @ruribev, 

Thank you for your message. 

Have you tried to look into the vignette and the manual of BayLum: [https://crp2a.github.io/BayLum/articles/BayLum.html](https://crp2a.github.io/BayLum/articles/BayLum.html) (also accessible via the R terminal). You get a detailed description in the file `Generate_DataFile()` (`?BayLum::Generate_DataFile` in the R terminal).

I hope this helps, 

Sebastian 

P.S.: I will this issue because your entry does not describe a bug.
